<template>
    <component
        :is="iconComponent"
        :size="size"
        :stroke-width="strokeWidth"
        class="chat-icon"
        aria-hidden="true"
    />
</template>

<script setup>
import { computed } from 'vue';
import {
    Ambulance,
    Anvil,
    Apple,
    ArrowLeft,
    ArrowRightFromLine,
    BriefcaseMedical,
    BroomSparkles,
    Bubbles,
    Calendar,
    CalendarCheck,
    CalendarClock,
    Car,
    Check,
    Cog,
    ChevronRight,
    CreditCard,
    Faucet,
    File,
    FileCheck,
    FlaskConical,
    Fuel,
    GlobeCheck,
    Hash,
    Headphones,
    Heart,
    Home,
    House,
    Info,
    LifeBuoy,
    LockOpen,
    Logs,
    Lock,
    Mail,
    MapPin,
    MirrorRectangular,
    Motorbike,
    Van,
    Bus,
    Caravan,
    Phone,
    Send,
    Handshake,
    Shield,
    ShoppingCartPlus,
    Smartphone,
    Sparkles,
    Star,
    StickyNote,
    ToothbrushSparkles,
    Toolbox,
    Truck,
    Unplug,
    UserStar,
    Wrench,
    X,
    Zap,
} from '@lucide/vue';

const props = defineProps({
    name: { type: String, default: 'chevron-right' },
    size: { type: [Number, String], default: 20 },
    strokeWidth: { type: [Number, String], default: 1.75 },
});

const ICONS = {
    'chevron-right': ChevronRight,
    'map-pin': MapPin,
    home: Home,
    house: House,
    car: Car,
    motorbike: Motorbike,
    van: Van,
    bus: Bus,
    caravan: Caravan,
    'toothbrush-sparkles': ToothbrushSparkles,
    'arrow-left': ArrowLeft,
    heart: Heart,
    truck: Truck,
    shield: Shield,
    star: Star,
    'lock-closed': Lock,
    beaker: FlaskConical,
    headset: Headphones,
    lifebuoy: LifeBuoy,
    'life-buoy': LifeBuoy,
    fuel: Fuel,
    unplug: Unplug,
    'lock-open': LockOpen,
    smartphone: Smartphone,
    faucet: Faucet,
    zap: Zap,
    anvil: Anvil,
    'mirror-rectangular': MirrorRectangular,
    'broom-sparkles': BroomSparkles,
    bubbles: Bubbles,
    check: Check,
    cog: Cog,
    'x-mark': X,
    envelope: Mail,
    'credit-card': CreditCard,
    calendar: Calendar,
    'calendar-check': CalendarCheck,
    'calendar-clock': CalendarClock,
    ambulance: Ambulance,
    'briefcase-medical': BriefcaseMedical,
    apple: Apple,
    'globe-check': GlobeCheck,
    sparkles: Sparkles,
    hashtag: Hash,
    send: Send,
    info: Info,
    logs: Logs,
    toolbox: Toolbox,
    handshake: Handshake,
    'shopping-cart-plus': ShoppingCartPlus,
    'sticky-note': StickyNote,
    'arrow-right-from-line': ArrowRightFromLine,
    file: File,
    phone: Phone,
    'user-star': UserStar,
    'file-check': FileCheck,
    wrench: Wrench,
};

const iconComponent = computed(() => ICONS[props.name] || ChevronRight);
</script>
